<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>

    jQuery( document ).ready(function() {

      jQuery('#btn-calculate-shipping').click(function() {
        billing.save()
        if(jQuery('.validation-advice').length >0)
          return false;
        shipping.save();
        jQuery(this).hide()
        jQuery('#shipping-method-please-wait').show();
        checkRateExist();
      });

      function checkRateExist() {
        if(jQuery('#checkout-shipping-method-load').find('.sp-methods').length > 0){
          shippingMethod.save();
          jQuery('#shipping-method-please-wait').hide();
          checkPaymentExist();
        }
        else
          setTimeout(function(){ checkRateExist(); }, 100);
      }

      function checkPaymentExist() {
        if(jQuery('#checkout-payment-method-load').children().length > 0){
          jQuery('#p_method_checkmo').prop("checked", true);
          jQuery('#place-order').show();
          payment.save();
        }
        else
          setTimeout(function(){ checkPaymentExist(); }, 100);
      }
    });

    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <!-- <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p> -->
        <button type="button" id="btn-calculate-shipping" class="btn-purple"><span><span><?php echo $this->__('Calculate') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Calculating ...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Calculating ...')) ?>" class="v-middle" /> <?php echo $this->__('Calculating ...') ?>
        </span>
    </div>
</form>
